<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>GymManagement.Web</RootNamespace>
    <UserSecretsId>GymManagement-DBMS330284-Local</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.3" />
  </ItemGroup>
</Project>
